version: "3"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ksquare
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - database:/var/lib/mysql
      - ./.docker/mysql/conf:/etc/mysql/conf.d
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: .docker/backend.dockerfile
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - EMAIL_API_KEY
      - EMAIL_DOMAIN
      - EMAIL_FROM_ADDRESS
      - GOOGLE_CLIENT_ID
      - HOME
      - JWT_SECRET
      - KEY_SERVICE_ACCOUNT
      - LOG_LEVEL
      - NODE_ENV
      - SERVER_PORT=8888
      - SERVICE_ACCOUNT
      - TIMEZONE
      - URLS_API_ROOT
      - URLS_PORT
      - URLS_PROTOCOL
      - URLS_URL
      - SLACK_ACCESS_TOKEN
      - SLACK_SIGNING_SECRET
      - SLACK_API_URI
      - SLACK_DUMMY_USER_ID
      - SLACK_CALLBACK_URL
    ports:
      - "8888:${SERVER_PORT}"

volumes:
  database: {}
